### ISSUE TITLE
知识广场的界面

### ISSUE THREAD

**Issue by wangxh89** [Yuyz0112/dewhale#119]
帮我实现下图中 知识广场 的界面
![IMG_6741](https://github.com/Yuyz0112/vx.dev/assets/6014585/a76c7cd3-d380-42e5-9e1f-d3b7213bda49)

**Comment by wangxh89** [comment]
<img width="1057" alt="image" src="https://github.com/Yuyz0112/vx.dev/assets/6014585/ab962d68-967d-4168-a353-5cc7c82c7460">
生成报错了

**Comment by Yuyz0112** [comment]
star 后可以体验三次
