### ISSUE TITLE
Space Quiz game

### ISSUE THREAD

**Issue by sulemanpervez** [Yuyz0112/dewhale#153]
"Develop an interactive AI Space Quiz game website that challenges users with intriguing questions about astronomy, space exploration, and celestial bodies. Engage players with a user-friendly interface, captivating visuals, and real-time scoring, fostering an immersive and educational experience. Incorporate diverse question formats, including multiple-choice, true/false, and fill-in-the-blanks, ensuring a dynamic and varied gameplay. Implement a leaderboard system to encourage friendly competition, allowing users to track their progress and compare scores with fellow space enthusiasts. Optimize the website for both desktop and mobile devices, ensuring accessibility for users to enjoy the AI-driven Space Quiz game anytime, anywhere."

**Comment by sulemanpervez** [comment]
just testing

**Comment by Yuyz0112** [comment]
@sulemanpervez Hi, you can experience it three times after star this repo.
