### ISSUE TITLE
an app to draw UML elements to design logic flow of python programs

### ISSUE THREAD

**Issue by fdovila** [Yuyz0112/dewhale#162]
a simple app to draw UML elements to design logic flow of python programs
building blocks on the left, drag and drop and connect. A right bar that shows the PlantUML corresponding to the diagram. The user can draw UML or write PlantUML.

**Comment by Yuyz0112** [comment]
@fdovila Hi, you can experience it three times after star this repo.

**Comment by fdovila** [comment]
> @fdovila Hi, you can experience it three times after star this repo.

done :)
