### ISSUE TITLE
生成一个列表页面，需要分页

### ISSUE THREAD

**Issue by xiongpf** [Yuyz0112/dewhale#163]
生成一个PC列表页面，可以自适应PC，mobile，需要分页。页面元素：title，content, image,address，link，布局左边图片，右边信息，点击链接可以跳转到详情页。技术要求：nextjs，Tailwind CSS，要求支持seo适配

**Comment by Yuyz0112** [comment]
@xiongpf Hi, you can experience it three times after star this repo.
